version: '3'
services:
  stacktweetbot:
    container_name: stacktweetbot
    image: seabbs/stacktweetbot:latest
    expose:
      - 8787
    ports:
      - 8787:8787
    environment:
      - USER=StackTweetBot
      - PASSWORD=StackTweetBot
